name: tests

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]
  push:
    branches:
      - main

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      SKIP_LABEL_CHECK: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production'}}
    steps:
      - name: Skip job and mark PR if label is not present
        if: contains(github.event.pull_request.labels.*.name, 'run-e2e-tests') == false && !github.env.SKIP_LABEL_CHECK
        run: |
          echo "E2E tests label not present. Skipping job."
          echo "branch $SKIP_LABEL_CHECK"
          echo "::error:: run-e2e-tests label not present. This job is required for merging PRs."
          exit 1

      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - run: bun --version
