name: tests

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]
  push:
    branches:
      - main

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      EVENT_NAME: ${{ github.event_name }}
      ACTION: ${{ github.event.action }}
      MERGED: ${{ github.event.pull_request.merged }}
      BRANCH: ${{ github.ref }}
    steps:
      - name: Skip job and mark PR if label is not present
        if: ${{contains(github.event.pull_request.labels.*.name, 'run-e2e-tests') == false && github.ref != 'refs/heads/main'}}
        run: |
          echo "E2E tests label not present. Skipping job."
          echo "event name $EVENT_NAME, action $ACTION, merged $MERGED, branch $BRANCH"
          echo "::error:: run-e2e-tests label not present. This job is required for merging PRs."
          exit 1

      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - run: bun --version
