name: tests

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]
  push:
    branches:
      - main

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      NOT_MAIN_BRANCH: ${{ !(github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production') }}
      LABEL_IS_MISSING: ${{ !contains(github.event.pull_request.labels.*.name, 'run-e2e-tests') }}
    steps:
      - name: Skip job and mark PR if label is not present
        if: ${{ github.env.LABEL_IS_MISSING }}
        run: |
          echo "E2E tests label not present. Skipping job."
          echo $LABEL_IS_MISSING $NOT_MAIN_BRANCH
          echo "::error:: run-e2e-tests label not present. This job is required for merging PRs."
          exit 1
      - name: Actual step
        run: echo $LABEL_IS_MISSING $NOT_MAIN_BRANCH
